export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const TOGGLE_PRODUCTS = 'TOGGLE_PRODUCTS';
export const TOGGLE_PRODUCT = 'TOGGLE_PRODUCT';
export const TOGGLE_PRODUCT_LOADING = 'TOGGLE_PRODUCT_LOADING';